__author__ = "Gianluca"
__copyright__ = "Copyright 2018"
__license__ = "MIT"
__version__ = "0.0.1"
__maintainer__ = "datatrading"
__email__ = ""
__status__ = "Development"
__url__ = "https://github.com/datatrading-info/datatrader"
